Some fixes for pacemaker-1.1.16
pcs property requires some time to settle
pcs resource create primary Dummy returns
Error: Multiple agents match 'Dummy', please specify full name:
ocf:heartbeat:Dummy, ocf:pacemaker:Dummy